[package]
name = "cargo-smart-build"
version = "0.2.0"
edition = "2024"
description = "Interactive cargo subcommand to easily select, configure, and build workspace crates with remembered preferences."
license = "MIT"
repository = "https://github.com/Lu-TheCoder/cargo-smart-build"
keywords = ["cargo", "build", "workspace", "incremental", "cli"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
serde = { version="1.0.228", features = ["derive"] }
cargo_metadata = "0.23.1"
dialoguer = "0.12.0"
anyhow = "1.0.101"
serde_json = "1.0.149"
dirs = "6.0.0"
console = "0.16.2"
